added cloud build monitoring

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,9 +34,23 @@ jobs:
 
       - run:
           name: Déclencher le Build Cloud Build
-          command: gcloud builds triggers run bf9e3d60-bed9-4322-a21a-ea854bd5cba8
-          environment:
-            CLOUDSDK_COMPUTE_REGION: europe-west1  # Spécifiez la région Cloud Build
+          command: |
+            BUILD_ID=$(gcloud builds triggers run bf9e3d60-bed9-4322-a21a-ea854bd5cba8 --format='value(metadata.build_id)')  # Obtenir l'ID du build
+            echo "Build ID: $BUILD_ID"
+
+      - run:
+          name: Surveiller le Build
+          command: |
+            STATUS=""
+            while [[ "$STATUS" != "SUCCESS" && "$STATUS" != "FAILURE" ]]; do
+              STATUS=$(gcloud builds describe $BUILD_ID --format='value(status)')  # Obtenir le statut du build
+              echo "Build Status: $STATUS"
+              sleep 10  # Pause avant de vérifier à nouveau
+            done
+            if [ "$STATUS" = "FAILURE" ]; then
+              echo "Build Failed"
+              exit 1  # Arrête le job si le build a échoué
+            fi
 
 workflows:
   ci-cd:
